name: Build Launcher
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build with PyInstaller
        run: |
          # Собираем в папку, а не в один файл
          # Используем --collect-all для надежного захвата зависимостей
          pyinstaller --noconsole \
          --collect-all PyQt6 \
          --collect-all minecraft_launcher_lib \
          --add-data "assets;assets" \
          main.py
          
      - uses: actions/upload-artifact@v4
        with:
          name: NovaLauncher-Build
          path: dist/
