name: Build Launcher
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build with PyInstaller
        run: |
          # Находим точное местоположение плагинов PyQt6
          QT_PLUGINS=$(python -c "import PyQt6; import os; print(os.path.join(os.path.dirname(PyQt6.__file__), 'Qt6', 'plugins'))")
          echo "Путь к плагинам: $QT_PLUGINS"
          
          # Запускаем сборку
          pyinstaller --noconsole \
          --collect-all PyQt6 \
          --collect-all minecraft_launcher_lib \
          --add-data "$QT_PLUGINS/platforms;PyQt6/Qt6/plugins/platforms" \
          --add-data "assets;assets" \
          main.py
          
      - uses: actions/upload-artifact@v4
        with:
          name: NovaLauncher-Build
          path: dist/
